name = "Nemonuri-Study-StanfordOnline-Compilers"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Nemonuri.Study.StanfordOnline.Compilers"]


[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "Nemonuri.Study.StanfordOnline.Compilers"
